services:
  - type: web
    name: city-events-backend
    env: python
    buildCommand: "./build.sh"
    startCommand: "cd backend && gunicorn config.wsgi:application"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0